Gjestebok/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include("guest_book.urls")),
    url(r'^admin/', admin.site.urls),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guest_book/urls.py
from django.conf.urls import url

from . import views
from .views import MemberCreate
app_name = "guest_book"

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^members/$', views.members, name = "members"),
    url(r'^entries/$', views.Entries.as_view() , name = "entries"),
    url(r'^entries/search_entries/$', views.search_entries , name = "search_entries"),
    url(r'^entries/edit/(?P<pk>[0-9]+)/$', views.EditEntry.as_view(), name = "edit_entry"),
    url(r'^entries/delete/(?P<pk>[0-9]+)/$', views.EntryDelete.as_view(), name = "delete_entry"),
    url(r'^new_entry/$', views.NewEntry.as_view(), name = "new_entry"),
    url(r'^members/(?P<member_id>[0-9]+)', views.member_detail, name = "member_detail"),
    url(r'^members/new_member/$', MemberCreate.as_view(), name = "new_member"),
    url(r'^members/edit/(?P<member_id>[0-9]+)/$', views.edit_member, name = "edit_member"),
    url(r'^members/delete/(?P<pk>[0-9]+)/$', views.MemberDelete.as_view(), name = "delete_member"),
    ]

guest_book/models.py
from datetime import datetime
from dateutil.relativedelta import relativedelta

from django.db import models
from django.utils import timezone
from django_resized import ResizedImageField

class Member(models.Model):
    first_name = models.CharField("fornavn", max_length=50)
    last_name = models.CharField("etternavn", max_length=50)
    phone = models.CharField("mobilnummer", max_length=20, null=True, blank=True)
    number_of_entries = models.IntegerField(default = 0)
    profile_photo = ResizedImageField(null = True, blank = True, verbose_name="profilbilde")
    email = models.EmailField(
        verbose_name = "e-post",
        max_length=255,
        unique=True,
        blank=True,
        null=True)
    about_me = models.TextField("litt om meg selv", blank=True, default="")
    birth_date = models.DateField("Fødselsdato", default=datetime.now)
    def __str__(self):
        return self.first_name + " " + self.last_name
    
    def get_age(self):
        return relativedelta(timezone.localdate(), self.birth_date).years

    # to check age of members at a certain time, use time.date()
    def get_age_at(self, date):
        return relativedelta(date, self.birth_date).years

class Entry(models.Model):
    author = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name="forfatter")
    pub_date = models.DateTimeField("dato publisert", default=datetime.now)
    title = models.CharField(max_length=255, unique=False, verbose_name="tittel")
    text = models.TextField("tekst")
    image = ResizedImageField(blank = True, null = True, verbose_name="bilde")
    members_involved = models.ManyToManyField(Member,
                                              blank=True,
                                              related_name="involved_entries",
                                              verbose_name="medlemmer med")
    def __str__(self):
        return self.title + " av " + self.author.__str__()
    
    def save(self, *args, **kwargs):
        """
        saves the object to the database, upping number_of_entries
        of the related user.
        """
        self.author.number_of_entries += 1
        self.author.save()

        super(Entry, self).save(*args, **kwargs)
        if not self.author in self.members_involved.all():
            self.members_involved.add(self.author)

    def get_author_age_at_creation(self):
        return relativedelta(self.pub_date.date(), self.author.birth_date).years

#TODO: change from pub_date to pub_time

guest_book/forms.py
from django import forms

from .models import Member, Entry

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['first_name', 'last_name', 'birth_date', 'phone', 'email', 'about_me', 'profile_photo']

class EntryAddForm (forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["author", "title", "pub_date", "text", "members_involved", "image"]

    def save(self, *args, **kwargs):
        obj = super(EntryAddForm, self).save(*args, **kwargs)
        # As djange resets manyToMany-fields after calling save from a
        # form, this line is necessary
        if not obj.author in obj.members_involved.all():
            obj.members_involved.add(obj.author) 
        return obj

guest_book/views.py
from django.shortcuts import render
from .models import Entry, Member
from .forms import EntryAddForm, MemberForm
from django.http import Http404
from django.http import HttpResponseRedirect
from django.forms import ModelForm
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from datetime import datetime
import pytz

def index(request):
    members = Member.objects.all()
    last_entries = Entry.objects.all().order_by("-pub_date")[:5];
    context = {"entries":last_entries}
    return render(request, "guest_book/index.html", context)

def members(request):
    members = Member.objects.all()
    context = {"members":members}
    return render(request, "guest_book/members.html", context)

def search_entries(request):
    return render(request, "guest_book/search_entries.html",{})

def member_detail(request, member_id):
    try:
        member = Member.objects.get(pk=member_id)
    except Member.DoesNotExist:
        raise Http404("Medlem eksisterer ikke")
    
    author_entries = Entry.objects.filter(author=member).order_by("-pub_date")
    involved_entries = member.involved_entries.exclude(author=member).order_by("-pub_date")

    context = {"member":member,
               "author_entries":author_entries,
               "involved_entries":involved_entries}
    return render(request, "guest_book/member_detail.html", context)

class Entries(ListView):
    template_name = "guest_book/entries.html"
    model = Entry
    context_object_name = "entries"
    paginate_by = 5
    def get_queryset(self):
        objects = Entry.objects.all()
        get_data = self.request.GET

        if "before_date" in self.request.GET:
            if get_data["before_date"] != "":
                before_date=datetime.strptime(get_data["before_date"], "%Y-%m-%d")
                before_date_aware=pytz.utc.localize(before_date)
                objects = objects.filter(pub_date__lte=before_date_aware)

        if "search_for" in get_data:
            if get_data["search_for"] != "":
                title_objects = objects.filter(title__contains=get_data["search_for"])
                content_objects = objects.filter(text__contains=get_data["search_for"])
                objects = title_objects.union(content_objects)

        return objects.order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # creates a get_string to be able to make links to other pages
        # of a search (pagination). Also creates "search descriptive" 
        # string to let the user know what was searched for
        get_data = self.request.GET
        get_string=""
        search_descriptive_string=""
        if "search_for" in get_data:
            get_string += "&search_for="
            get_string += get_data["search_for"]
            if get_data["search_for"] != "":
                search_descriptive_string += ("med frasen \"" + get_data["search_for"] + "\" ")
        if "before_date" in get_data:
            get_string += "&before_date="
            get_string += get_data["before_date"]
            if get_data["before_date"] != "":
                search_descriptive_string += ("før \"" + get_data["before_date"] + "\" ")
        context["get_string"] = get_string
        context["descriptive_string"] = search_descriptive_string
        return context

def edit_member(request, member_id):
    try:
        member = Member.objects.get(pk=member_id)
    except Member.DoesNotExist:
        raise Http404("Medlem eksisterer ikke")
    
    #This is a form request for someone who has filled out the form
    if request.method == "POST":
        form = MemberForm(request.POST, request.FILES, instance = member)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("guest_book:members"))

    form = MemberForm(instance=member)
    context = {"form":form, "member":member}
    return render(request, "guest_book/edit_member.html", context)

class MemberCreate(CreateView):
    template_name = "guest_book/create_member.html"
    model = Member
    fields = ['first_name', 'last_name', 'birth_date', 'phone', 'email', 'about_me', 'profile_photo']
    success_url = reverse_lazy("guest_book:members")

class MemberDelete(DeleteView):
    template_name = "guest_book/confirm_delete_member.html"
    model = Member
    success_url = reverse_lazy("guest_book:members")

class NewEntry(CreateView):
    template_name = "guest_book/new_entry.html"
    model = Entry
    form_class = EntryAddForm
    success_url = reverse_lazy("guest_book:entries")

class EditEntry(UpdateView):
    template_name = "guest_book/edit_entry.html"
    model = Entry
    form_class = EntryAddForm
    success_url = reverse_lazy("guest_book:entries")

class EntryDelete(DeleteView):
    template_name = "guest_book/confirm_delete_entry.html"
    model = Entry
    success_url = reverse_lazy("guest_book:entries")

guest_book/templates/guest_book/base.html
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'guest_book/styles.css' %}" />
{% endblock stylesheets %}
{% block header %}
  <div id="header">
    <div id="heading">
      <h1><a href="{% url 'guest_book:index' %}">Hytteboka</a></h1>
    </div>
    <ul>
      <li class="menu-item"><a href="{% url 'guest_book:new_entry' %}">Nytt innlegg</a></li>
      <li class="menu-item"><a href="{% url 'guest_book:members' %}">Medlemmer</a></li>
      <li class="menu-item"><a href="{% url 'guest_book:entries' %}">Innlegg</a></li>
      <li class="menu-item"><a href="{% url 'guest_book:search_entries' %}">Søk etter innlegg</a></li>
    </ul>
  </div>
{% endblock header %}

<div id="content-container">
  {% block content %}{% endblock content %}
</div>

guest_book/templates/guest_book/confirm_delete_entry.html
{% extends 'guest_book/base.html' %}

{% block content %}
<h1>Slett innlegg</h1>
<form action="" method="post">{% csrf_token %}
    <p>Er du sikker på at du vil slette "{{ object }}"?</p>
    <input type="submit" value="Slett" />
</form>
{% endblock content %}

guest_book/templates/guest_book/confirm_delete_member.html
{% extends 'guest_book/base.html' %}

{% block content %}
<h1>Slett medlem</h1>
<form action="" method="post">{% csrf_token %}
    <p>Er du sikker på at du vil slette "{{ object }}"?</p>
    <input type="submit" value="Slett" />
</form>
{% endblock content %}

guest_book/templates/guest_book/create_member.html
{% extends 'guest_book/base.html' %}

{% block content %}
<h1>Legg til nytt medlem</h1>

<div width=500px>
  <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
  </form>
</div>
{% endblock content %}

guest_book/templates/guest_book/edit_entry.html
{% extends 'guest_book/base.html' %}

{% block content %}
<h1>Endre innlegg</h1>

<form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Lagre"/>
</form>
{% endblock content %}

guest_book/templates/guest_book/edit_member.html
{% extends 'guest_book/base.html' %}

{% block content %}
<h1>Endre medlem - {{ member }}:</h1>
<div width=500px>
  <form enctype="multipart/form-data" action="{% url 'guest_book:edit_member' member.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Lagre" />
  </form>
</div>
{% endblock content %}

guest_book/templates/guest_book/entries.html
{% extends 'guest_book/base.html' %}

{% block content %}
<h1>Alle innlegg {{ descriptive_string }}</h1>
{% if not entries %}
  <h2>Det er ingen innlegg ennå</h2>
{% else %}
  {% include 'guest_book/entries_paginated' %}
{% endif %}
{% endblock content %}

guest_book/templates/guest_book/entry_base.html
{% load entry_extras %}
{% load i18n %}
<div class="entry-container">
<h3>{{ entry.title }}</h2>
{% if entry.image %}
  <img class="entry-image" src="{{ entry.image.url }}", alt="bilde">
{% endif %}
<p>publisert {{ entry.pub_date|date:'l d. F o, H:i' }} av {{ entry.author }}</p>
{% if entry.members_involved %}
  <h4>De som var med:</h4>
  <ul>
    {% for involved_member in entry.members_involved.all %}
      <li><a href = "{% url 'guest_book:member_detail' involved_member.id %}">{{ involved_member }}</a> - {% age_at involved_member entry %} år</li>
    {% endfor %}
  </ul>
{% endif %}
<p>{{ entry.text }}</p>
{% block edit_links %}{% endblock edit_links %}
</div>

guest_book/templates/guest_book/entry_base_edit.html
{% extends 'guest_book/entry_base.html' %}
{% block edit_links %}
  <p><a href="{% url 'guest_book:edit_entry' entry.id %}">endre innlegg</a> - 
  <a href="{% url 'guest_book:delete_entry' entry.id %}">slett innlegg</a></p>
{% endblock edit_links %}

guest_book/templates/guest_book/index.html
{% extends 'guest_book/base.html' %}

{% block content %}
  <div class="entry-container"><h1>Hallo og velkommen til hytteboken!</h1></div>
  {% if not entries %}
    <h2>Det er ingen innlegg ennå</h2>
  {% else %}
    <h2>Siste innlegg:</h2>
    {% for entry in entries %}
      {% include "guest_book/entry_base.html" with entry=entry %}
    {% endfor %}
  {% endif %}
{% endblock content %}

guest_book/templates/guest_book/member_detail.html
{% extends 'guest_book/base.html' %}
{% load i18n %}

{% block content %}
<h1>{{ member }} - {{ member.get_age }} år</h1>
{% if member.profile_photo %}
  <img id="member-photo" src="{{ member.profile_photo.url }}", alt="profile picture">
{% endif %}
<h3>Fødselsdato: {{ member.birth_date|date:'d F o' }}</h3>
{% if member.email %}
  <h3>E-mail: {{ member.email }}</h3>
{% endif %}
{% if member.phone %}
  <h3>Telefonnummer: {{ member.phone }}</h3>
{% endif %}
{% if member.about_me %}
  <h3>Om meg selv: {{ member.about_me }}</h3>
{% endif %}
<hr>
{% if author_entries %}
  <h2>Innlegg skrevet:</h2>
  {% for author_entry in author_entries %}
    {% include "guest_book/entry_base.html" with entry=author_entry %}
  {% endfor %}
{% else %}
  <h2>{{ member.first_name }} har ikke skrevet noen innlegg ennå </h2>
{% endif %}
<hr>
{% if involved_entries %}
  <h2>Innlegg vært med på:</h2>
  {% for involved_entry in involved_entries %}
    {% include "guest_book/entry_base.html" with entry=involved_entry %}
  {% endfor %}
{% else %}
  <h2>{{ member.first_name }} finnes ikke i noen andre innlegg</h2>
{% endif %}
{% endblock content %}

guest_book/templates/guest_book/members.html
{% extends 'guest_book/base.html' %}

{% block content %}
<h1>Medlemsliste</h1>
{% if members %}
  {% for member in members %}
    <ul>
      <li><a href="{% url 'guest_book:member_detail' member.id %}">{{ member }}: {{ member.get_age }} år</a> - <a href="{% url 'guest_book:edit_member' member.id %}">endre</a> - <a href="{% url 'guest_book:delete_member' member.id %}">slett</a></li>
    </ul>
  {% endfor %}
{% else %}
  <p>There´s no members</p>
{% endif %}
<h2><a href="{% url 'guest_book:new_member' %}">Legg til nytt medlem</a></h2>
{% endblock content %}

guest_book/templates/guest_book/new_entry.html
{% extends 'guest_book/base.html' %}

{% block content %}
<h1>Lag nytt innlegg</h1>

<div width=500px>
  <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Lagre" />
  </form>
</div>
{% endblock content %}

guest_book/templates/guest_book/search_entries.html
{% extends 'guest_book/base.html' %}

{% block content %}
<form action="{% url 'guest_book:entries' %}" method="get">
  Søk etter:
  <input type="text" name="search_for">
  Innlegg før:
  <input type="date" name="before_date">
  <input type="submit" value="Søk"/>
</form>
{% endblock content %}